medias:
  - name: "Le Monde"
    domain: "lemonde.fr"
  - name: "France 24"
    domain: "france24.com"
  - name: "20 Minutes"
    domain: "20minutes.fr"
  - name: "Le Figaro"
    domain: "lefigaro.fr"
  - name: "Les Echos"
    domain: "lesechos.fr"
  - name: "Libération"
    domain: "liberation.fr"
  - name: "La Croix"
    domain: "la-croix.com"
  - name: "Le Parisien"
    domain: "leparisien.fr"
  - name: "La Dépêche"
    domain: "ladepeche.fr"
  - name: "L'Obs"
    domain: "nouvelobs.com"

